-- Simplify roles: GUEST/HOST → USER, keep ADMIN
UPDATE "User" SET "role" = 'USER' WHERE "role" IN ('GUEST', 'HOST');
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE TEXT;
DROP TYPE "Role" CASCADE;
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN');
ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role" USING "role"::"Role";
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'USER';
